name: CI/CD Pipeline
on: [push, pull_request, workflow_dispatch]
jobs:
  linting:
    name: Run Lint Checks
    runs-on: ubuntu-latest
    steps:
      - name: 1. Fetch repository
        uses: actions/checkout@v4

      - name: 2. Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Set Up pnpm
        uses: pnpm/action-setup@v2
      
      - name: 4. Install dependencies --frozen-lockfile
        run: pnpm install

      - name: 5. Lint checks
        run: pnpm lint
        env:
          SKIP_ENV_VALIDATION: true

      - name: 6. Typecheck
        run: pnpm typecheck

      - name: 7. Prettier Check
        run: pnpm format:check

  testing:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: 1. Fetch repository
        uses: actions/checkout@v4

      - name: 2. Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Set Up pnpm
        uses: pnpm/action-setup@v2
      
      - name: 4. Install dependencies --frozen-lockfile
        run: pnpm install

      - name: 5. Run unit tests
        run: pnpm test:ci
        env:
          SKIP_ENV_VALIDATION: true
